### ISSUE TITLE
Duplicated comments on fixed issue

### ISSUE THREAD

**Issue by drakhart** [nearform/optic-release-automation-action#150]
Optic bot commented four times in a row that the issue was resolved by release X here: https://github.com/nearform/mercurius-apollo-tracing/issues/125

Steps we followed:
- I created a new patch release (v1.0.2) via workflow.
- I don't have permissions for publishing to npm (I didn't know at the time).
- I merged the PR anyway.
- @simoneb warned meabout permissions, and he created a new patch release (v1.0.3).
- He merged the PR.
- After that I looked at the original issue and saw four comments from Optic bot saying that "🎉 This issue has been resolved in version 1.0.2 🎉"
- All four mentioned 1.0.2, none of them 1.0.3.
- Two were created at the same time right after my merge, another two at the same time after Simone's merge (5 minutes difference).
- Unfortunately I removed all the duplicates and left only one comment, which I also updated to reflect v1.0.3, so the issue wasn't polluted with wrong information.

**Comment by CristiTeo** [comment]
I created from scratch an empty repository where I 
 added the configuration for `optic-release-automation-action`.
I did a couple of testing and PR where I test if I can catch this issue.
I did the following tests scenarios: 
- I created a normal PR, merged it and started `release` action, everything works as expected.
- I created 2 PR, merged them at the same time, and started `release` action, works without any issue.
- I create 2 PR, merged them, and created 2 releases, merged them, and everything worked.
- I tried to follow the scenario from ...., but without success.

Because I couldn't find the right way to get this issue I will close it.
