### ISSUE TITLE
Sanity check: is the action releasing the right version or the latest commit?

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#167]
When a PR created by the action gets merged, which version of the repo is released exactly? 

E.g.

- PR opened in a branch with commit 1
- commits 2, 3, 4 are done on master
- PR merged, causing merge commit 5

Theoretically, the semantics of the action should lead to the result of merging commit 1 to the master branch to be released, but I guess that what's happening now is that all commits in between will end up in the release.

We need to figure out if there's a way to make this work according to correct semantics.

**Comment by guilhermelimak** [comment]
You're correct, all commits that are on the master branch at the time of the merge are included in the release.
I've opened PRs on both the [action](https://github.com/nearform/optic-release-automation-action/pull/171) and the [app](https://github.com/nearform/optic-release-automation-app/pull/158) with a suggestion for a fix using the `target_commitish` parameter when creating the release as shown [here](https://docs.github.com/en/rest/releases/releases#create-a-release--parameters) but I'm not entirely sure that works since I wasn't able to test it yet.

Is [https://github.com/nearform/optic-release-automation-app#development](this) the correct way to deploy a testing version of the app or is there an easier way? If that's the only way is there a nearform gcp account that I can use to test this?

**Comment by simoneb** [comment]
Thanks for looking into this! I think the easiest way to test this is to run the app locally and expose it e.g. via nkgrok, then configure the action to use that url (it's one of the action's input). Definitely let's test this end to end before going any further, but I think the approach you're following is good 👌

**Comment by simoneb** [comment]
@guilhermelimak once the releases are done, please close this issue
