### ISSUE TITLE
Support multiple npm/optic tokens

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#18]
We want to be able to allow multiple people to release npm packages. This means we need multiple NPM tokens and multiple Optic tokens (if needed).

- To do this, the action should support both of the above either as single tokens (as it does now) or multiple.
- Because action inputs cannot be arrays, we need to decide on an encoding format for arrays of values. Because those values are coming from repo secrets, it should also be able to store them there. I would suggest using comma separated values, which should be safe as neither npm or optic tokens should contain commas

Once we have a way to provide arrays of tokens, the action must:

- parse them correctly
- [zip](https://en.wikipedia.org/wiki/Zipping_(computer_science)) the two arrays and validate that they have the same cardinality
- when doing the npm publish, iterate through the pairs and implement the same behavior as [Promise.race](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)

**Comment by salmanm** [comment]
Some thoughts

- Storing comma-separated tokens in GN secrets is tricky when you want to add a new member. Since GH secrets can not be retrieved and only updated, we won't be able to "append" a new token at the end. We'll always have to create new one's.
- Sending OTP requests to all tokens sounds a bit an overkill and may cause a bit of confusion among the people who are not aware of the new release happening. How about we do this instead?
  - Instead of `NPM_TOKEN` as one secret, we create `NPM_TOKEN_<username>` & `OPTIC_TOKEN_<username>`
  - So we'd have secrets that would look like
    - `NPM_TOKEN_salmanm`  = `NHGFHGMFHGH`
    - `OPTIC_TOKEN_salmanm` = `KHkVKHJKHJG`
    - `NPM_TOKEN_simoneb` = `7656JHBJHBBHJ`
    - `OPTIC_TOKEN_simoneb` = `SDTHJNVHJ`
    - Hence adding new members is easy as well as revoking someone's access is easy too.
  - In action, we'd have a simple util that will try to access ```secrets[`NPM_TOKEN_${github.actor}`]``` and use that.
  - If action does not find a secret, it can early exit.

How does that sound?

**Comment by simoneb** [comment]
Sounds great 👍

**Comment by simoneb** [comment]
@salmanm let's keep supporting the current approach so we're backwards compatible and we work well in single-maintainer scenarios where we don't need multiple tokens

**Comment by salmanm** [comment]
Sore, let's fallback to `NPM_TOKEN`
```const npmToken = secrets[`NPM_TOKEN_${github.actor}`]  || secrets['NPM_TOKEN']```

**Comment by ja-bravo** [comment]
I'll take this one following @salmanm idea of ```NPM_TOKEN_<username>``` & ```OPTIC_TOKEN_<username>```

**Comment by simoneb** [comment]
@sameer-coder is working on it as far as I know
