### ISSUE TITLE
Still not picking the last release correctly as the base

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#256]
See https://github.com/nearform/github-snooze-chrome-extension/pull/443.

It should have used 1.7.6 as the base release for generating the changelog (as it was the latest), instead it used 1.7.0 as the base.

Note this was supposed to be addressed in https://github.com/nearform/optic-release-automation-action/issues/195, but it seems to still be occurring for some reason.

**Comment by davideroffo** [comment]
The [GitHub Snooze Chrome Extension](https://github.com/nearform/github-snooze-chrome-extension) repository is not picking the proper base release because in the GitHub workflow [release.yml](https://github.com/nearform/github-snooze-chrome-extension/blob/master/.github/workflows/release.yml) file it's using a specific branch of optic-release-automation-action:

- `nearform/optic-release-automation-action@feat/add-monorepo-support`

instead of the latest `v4` release.

**Comment by davideroffo** [comment]
I created a PR ( https://github.com/nearform/github-snooze-chrome-extension/pull/463 ) to address the issue ( https://github.com/nearform/github-snooze-chrome-extension/issues/462 ) directly on the [GitHub Snooze Chrome Extension repository](https://github.com/nearform/github-snooze-chrome-extension).

**Comment by simoneb** [comment]
Good catch, we can close this issue
